/**
 * This Source Code Form is part of the HexaGlue project.
 * Copyright (c) 2025 Scalastic
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Commercial licensing options are available for organizations wishing
 * to use HexaGlue under terms different from the MPL 2.0.
 * Contact: info@hexaglue.io
 */
package io.hexaglue.spi.codegen;

import java.time.Instant;
import java.util.Objects;
import java.util.Optional;

/**
 * Represents a standard header that can be applied to generated artifacts.
 *
 * <p>Headers typically include:
 * <ul>
 *   <li>generation attribution ("Generated by HexaGlue")</li>
 *   <li>copyright/license</li>
 *   <li>generation timestamp (optional)</li>
 * </ul>
 *
 * <p>The header content is ultimately rendered by the compiler; this SPI type provides
 * stable, structured inputs.</p>
 */
public final class GeneratedHeader {

    private final String toolName;
    private final String license;
    private final String copyright;
    private final Instant generatedAt;

    private GeneratedHeader(String toolName, String license, String copyright, Instant generatedAt) {
        this.toolName = requireNonBlank(toolName, "toolName");
        this.license = normalizeBlankToNull(license);
        this.copyright = normalizeBlankToNull(copyright);
        this.generatedAt = generatedAt;
    }

    /**
     * Creates a header.
     *
     * @param toolName tool name (non-blank), e.g. "HexaGlue"
     * @param license license identifier or text (nullable)
     * @param copyright copyright line (nullable)
     * @param generatedAt generation timestamp (nullable)
     * @return header
     */
    public static GeneratedHeader of(String toolName, String license, String copyright, Instant generatedAt) {
        return new GeneratedHeader(toolName, license, copyright, generatedAt);
    }

    /**
     * Creates a minimal header for HexaGlue with no license/copyright.
     *
     * @return header
     */
    public static GeneratedHeader minimalHexaGlue() {
        return new GeneratedHeader("HexaGlue", null, null, null);
    }

    /** @return tool name (never blank) */
    public String toolName() {
        return toolName;
    }

    /** @return license if provided */
    public Optional<String> license() {
        return Optional.ofNullable(license);
    }

    /** @return copyright if provided */
    public Optional<String> copyright() {
        return Optional.ofNullable(copyright);
    }

    /** @return generation timestamp if provided */
    public Optional<Instant> generatedAt() {
        return Optional.ofNullable(generatedAt);
    }

    @Override
    public String toString() {
        return "GeneratedHeader{toolName=" + toolName + "}";
    }

    private static String requireNonBlank(String v, String label) {
        Objects.requireNonNull(v, label);
        String t = v.trim();
        if (t.isEmpty()) throw new IllegalArgumentException(label + " must not be blank");
        return t;
    }

    private static String normalizeBlankToNull(String v) {
        if (v == null) return null;
        String t = v.trim();
        return t.isEmpty() ? null : t;
    }
}
